# Generated by Django 3.2 on 2021-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
